/*
 * File: next.cpp
 * Author: Ashutosh Panigrahy
 * Created: 2026-04-11
 * Description: Varidaic templates, fold expressions, move semantics intro
 * https://share.google/aimode/shnZgiJWNlaINfYXt
 * https://www.youtube.com/watch?v=lyDGcdqEhqI&t=291s
 * TODO: https://stackoverflow.com/questions/980492/what-is-metaprogramming
 * NOTE: keep it working & simple
 */

#include <iostream>
#include <memory>
#include <string>

// TODO support variable number of arguments

template <typename T1> T1 sum_vals(T1 arg) { return arg; } // base-case

template <typename T1, typename... Args>
// type depends on first argument
T1 sum_vals(T1 first_val,
            Args const &...args) {      // param pack: >= 0 val as 1 entity
  return first_val + sum_vals(args...); // recursive-structure
}

template <typename... Args> auto add(Args... args) {
  // NOTE: fold expressions: concise syntax to reduce param pack over binary ops
  // fold expressions must be wrapped in parenthesis / both op must be SAME

  // fold expressions are available in a variety of flavors:
  // unary right (pack op ...) => (a1 op (a2 op (a3 op ... op (an)))
  // unary left (... op pack) => (an op (an-1 op (an-2 op ... op (a1)))
  // most unary folds fail on empty packs: only (&&, ||, ",") work

  // binary right (pack op ... op init)
  // => (a1 op (a2 op (a3 op ... op (an op init)))
  // binary left (init op ... op pack)
  // => (an op (an-1 op (an-2 op ... op (a1 op init)))

  // associativity matters for subtraction/division
  // subtract: (init - ... - args)
  return (0 + ... + args);
}

template <class T, typename... Args>
std::unique_ptr<T> make_unique_custom(Args &&...args) {
  // This is Pack Expansion, not a Fold Expression
  // new T(arg1, arg2, arg3)
  return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
}

int main() {
  // (i,f,d,i,i) -> (f,d,i,i) -> (d,i,i) -> (i,i) -> (i)
  std::cout << sum_vals(1, 1.0f, 3.7, 4, 5) << std::endl; // 14: int

  // (d,f,d,i,i) -> (f,d,i,i) -> (d,i,i) -> (i,i) -> (i)
  std::cout << sum_vals<double>(1, 1.0f, 3.7, 4, 5) << std::endl;

  // making the return type auto fixes the issue of manual type addition
  // template<> double sum_vals(i,f,d,i,i) generated by the compiler
  // NOTE:make the return type auto unless it actually matters to be a T
  // auto is cheap: only cost is type readability / no runtime costs

  // (i,f,d,f,f)
  std::cout << add(1, 3.1212f, 2.132323131, 4.11f, 3.56f) << std::endl;
  {
    struct Lyric {
      Lyric(std::string a, std::string c) { /* ... */ }
      Lyric(std::string a, std::string b, std::string c) { /* ... */ }
    };

    // compiler creates a make_unique_custom function template for Lyric
    // initializes a unique pointer to that lyric => RAII benefits
    // Lyric is composed of a var cnt of str args: match any constructor
    // Args temporary object takes in strings: no guarantees to its size
    // Hence, Args is passed in as an r-value reference. Create Lyric.

    // NOTE: benefit of elipsis ... in this case
    // allows a variable number of arguments as long as matching constructor

    // benefit of std::forward in this case: once args is inside the function
    // now a named reference -> compiler treats it as object with name & address
    // essentially, args is now an l-value -> invokes costly copy
    // std::forward helps to maintain it as an r-value -> allows move semantics

    // TODO: this is high level explanation. not studiet move semantics yet

    std::unique_ptr<Lyric> lyric_ptr_1 = make_unique_custom<Lyric>(
        "If you find one, please let me know", "what piece I've lost");

    std::unique_ptr<Lyric> lyric_ptr_2 = make_unique_custom<Lyric>(
        "If you find one, please let me know", "what piece I've lost",
        "Peel the scars from off my back");
  }

  // NOTE: decltype determines expression type without evaluating (compile-time)
  // meanwhile, auto evaluates type based on the calculated value of expression
  // TODO: https://www.scs.stanford.edu/~dm/blog/decltype.html
}
